FROM ubuntu

RUN apt-get update && apt-get install rsync

RUN ln -s /etc /tmp/master1 \
  && ln -s /tmp/master1 /tmp/master \
  && mkdir /tmp/slave1 \
  && ln -s /tmp/slave1 /tmp/slave

CMD [ "bash" ]
